### ISSUE TITLE
macOS

### ISSUE THREAD

**Issue by maxoux53** [TheDucky/Terminal-discord-presence#1]
hi
does it work on macOS?

**Comment by TheDucky** [comment]
hello,
YES! as macOS is Unix based it should work just fine. macOS loads bash as its default shell so the Unix script should detect it.

**Comment by maxoux53** [comment]
> hello,
> 
> YES! as macOS is Unix based it should work just fine. macOS loads bash as its default shell so the Unix script should detect it.

Ok thanks :)
