### ISSUE TITLE
Question for windows

### ISSUE THREAD

**Issue by AMufInABox** [TheDucky/Terminal-discord-presence#2]
Hey! I was wondering how I could potentially make this work with windows? As crontab isnt on windows.

**Comment by TheDucky** [comment]
Hey! 
Yes there is a work around to get this running on windows. check out these stackoverflow posts:
[Setting up a cron job in Windows](https://stackoverflow.com/questions/7195503/setting-up-a-cron-job-in-windows)
[How to start a python file while Windows starts?](https://stackoverflow.com/questions/4438020/how-to-start-a-python-file-while-windows-starts)
